### ISSUE TITLE
.dll problem when released

### ISSUE THREAD

**Issue by vlad12244** [arklumpus/MuPDFCore#12]
Hello. I released an app using MuPDF with windows forms .core 3.2. At my pc it worked fine, but on others it is saying that "Unable to load DLL MuPDFWrapper". Are there any dependencies besides core 3.2? Dll is right next to executable. I saw this (but see the note for .NET Framework). But it is telling about Framework not Core :) I guess it hasnt changed then(it worked when I installed that pack).

**Comment by arklumpus** [comment]
Hi! I assume this is on Windows, right?

The only other dependency should be this:

> **Note**: you should make sure that end users on Windows install the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, 2019 and 2022](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160#visual-studio-2015-2017-2019-and-2022) for their platform, otherwise they will get an error message stating that `MuPDFWrapper.dll` could not be loaded because a module was not found.

**Comment by vlad12244** [comment]
Thank you. It is solved.

**Comment by arklumpus** [comment]
Great!

**Comment by blackholeearth** [comment]
i have same exception . 
and MuPDFWrapper is not in the debug folder.  

im using .net 4.7.2  
installed latest vcredist from the link
