### ISSUE TITLE
Cannot open document

### ISSUE THREAD

**Issue by lijianxin520** [arklumpus/MuPDFCore#14]
![image](https://user-images.githubusercontent.com/47262889/149451738-398222c3-8fd5-45a9-914e-a2b647ddfe38.png)

**Comment by arklumpus** [comment]
Hi! What file are you trying to open? Where is it located?

**Comment by lijianxin520** [comment]
Hello, this is a file I tested and the location of the file ;I can open this file using the PDF tool. 
![image](https://user-images.githubusercontent.com/47262889/149454727-ca593750-d6be-4449-ae39-6f2c570fa1f8.png)

**Comment by arklumpus** [comment]
Ok, my first guess would be that the ideogram in the file name is causing the problem, can you try renaming the file?

**Comment by lijianxin520** [comment]
Thank you, I tried to rename the file, the test result is that the file name cannot contain Chinese characters;

**Comment by arklumpus** [comment]
This should be solved in MuPDFCore version 1.4.1! Feel free to reopen (or create a new issue) if you still have the problem.
