### ISSUE TITLE
do you support reading encrypted PDF files?

### ISSUE THREAD

**Issue by lijianxin520** [arklumpus/MuPDFCore#17]
Hello, do you support reading encrypted PDF files?

**Comment by arklumpus** [comment]
This is now implemented in MuPDFCore v.1.6.0. See the [page of the wiki](https://github.com/arklumpus/MuPDFCore/wiki/Working-with-password-protected-files) for information on how to check whether a file is encrypted an how to unlock it.

**Comment by lijianxin520** [comment]
Thank you very much for your support. I will try this version of yours. Thanks again!
