### ISSUE TITLE
PDFViewerDemo cannot chanage pages

### ISSUE THREAD

**Issue by shenlebantongying** [arklumpus/MuPDFCore#19]
I managed to build the demo from the current master, but the turn page doesn't even work.

Click the `^` & `v` only to change the number displayed and nothing else. Press enter also doesn't work.

![image](https://user-images.githubusercontent.com/20123683/188323219-5e9f86b8-ac8f-4471-9b47-82d690bc8be9.png)

**Comment by arklumpus** [comment]
Hi! Thanks for noticing this! It was a small bug in the viewer code, it should be fixed in the current master.

**Comment by shenlebantongying** [comment]
Thanks, it works now.
