### ISSUE TITLE
Set anti-aliasing level

### ISSUE THREAD

**Issue by ju5tas** [arklumpus/MuPDFCore#27]
Hi!
Native MuPDF library has the ability to set how many bits of anti-aliasing to use (fz_set_aa_level). The default value is 8.
But MuPdfCore has no such parameter in the WriteImage method.
Please add it, because sometimes anti-aliasing messes up schemes and fonts.

**Comment by arklumpus** [comment]
Hi, thank you for suggesting this - I will implement it as soon as I manage to have enough time to work on this and to also update the native MuPDF to the latest version!

**Comment by arklumpus** [comment]
This is now implemented in version 1.8.0:
  * The `MuPDFContext.GraphicsAntiAliasing` property can be used to get and set the graphics anti-aliasing.
  * The `MuPDFContext.TextAntiAliasing` property can be used to get and set the text anti-aliasing.
  * The `MuPDFContext.AntiAliasing` property (write-only) can be used to set both the graphics and text anti-aliasing to the same level.

I'm closing this issue, let me know if you have any other problems or suggestions.
