### ISSUE TITLE
is there a plan to support the outline

### ISSUE THREAD

**Issue by wolfweb** [arklumpus/MuPDFCore#29]

**Comment by arklumpus** [comment]
Hi, this should be doable, I can have a look for the next release!

**Comment by wolfweb** [comment]
Thank you for your prompt response 
Best Regards

**Comment by arklumpus** [comment]
Hi, this is now implemented in version 1.9.0. I'm closing this issue for now, feel free to reopen it (or to create a new one) if necessary!
