### ISSUE TITLE
Do you support deleting pages

### ISSUE THREAD

**Issue by azbo** [arklumpus/MuPDFCore#30]
Do you support deleting pages

**Comment by arklumpus** [comment]
Hi! Sure, you can use the `MuPDFDocument.CreateDocument` static method to create a new PDF file using only some pages from another document:

```CSharp
// Create a new context.
using MuPDFContext ctx = new MuPDFContext();

// Open a PDF document.
using MuPDFDocument doc = new MuPDFDocument(ctx, "path/to/inputFile.pdf");

// Create a list with all the pages in the document.
List<MuPDFPage> pagesToKeep = new List<MuPDFPage>(doc.Pages);

// Remove some pages.
pagesToKeep.Remove(doc.Pages[2]);
pagesToKeep.Remove(doc.Pages[4]);

// Create a new document with the specified pages.
MuPDFDocument.CreateDocument(ctx, "path/to/outputFile.pdf", DocumentOutputFileTypes.PDF, pages: pagesToKeep.ToArray());
```

**Comment by arklumpus** [comment]
Hi, I'm closing this - feel free to reopen it (or create a new issue) if you have any more questions or problems!

Also, please note that as of MuPDFCore v2.0.0, `MuPDFDocument.CreateDocument` is deprecated, and you should use `MuPDFDocument.Create.Document` or `MuPDFDocument.Create.PDFDocument` instead.
