### ISSUE TITLE
MuPDFPageCollection.GetEnumerator bug

### ISSUE THREAD

**Issue by thinker1990** [arklumpus/MuPDFCore#4]
Hi, there is a bug in MuPDFPageCollection.GetEnumerator implemention.

```
        public IEnumerator<MuPDFPage> GetEnumerator()
        {
            for (int i = 0; i < Pages.Length; i++)
            {
                if (Pages[i] == null)
                {
                    Pages[i] = new MuPDFPage(OwnerContext, OwnerDocument, i);
                }
            }

            return (IEnumerator<MuPDFPage>)Pages.GetEnumerator();
        }
```

The type of `Pages.GetEnumerator()` is `SZArrayEnumerator`, it can not be cast to `System.Collections.Generic.IEnumerator`.

![Invalid cast](https://user-images.githubusercontent.com/20510068/106375771-25950980-63ca-11eb-91db-b71cc1090436.png)

**Comment by arklumpus** [comment]
Thank you for spotting this! I have included your fix in version 1.2.4 (the NuGet package should become available as soon as it finishes validation and indexing).
