### ISSUE TITLE
JPX support disabled

### ISSUE THREAD

**Issue by Carael** [arklumpus/MuPDFCore#6]
When I try to export PNG image from an PDF that contains an image in JPEG2000 format I receive the "JPX support disabled" error.

That indicates that the support for those files were explicitly disabled with the "FZ_ENABLE_JPX" header (since it's enabled by default).

I've build everything from sources with default config.h headers and the PDF's with JPEG2000 files works correctly.

Did you disable it explicitly? If yes what was the reason. And if it an omission is it possible for you to release the new version with FZ_ENABLE_JPX enabled?

Thanks in advance.

**Comment by arklumpus** [comment]
Interesting, I don't think that was intentional... I will try to recompile everything, but in the mean time:

* What platform are you on?
* Can you send me a PDF showing the problem, so that I make sure that I solve it?
* If you are on Linux, do you still get the issue if you use version 1.2.4 of the library?

**Comment by Carael** [comment]
I'm on windows and there both versions (1.2.4 and 1.2.6) have this problem.

I've tested it on linux and there it works perfectly on both old and new version. Sadly I don't have a mac to test the mac version.

It looks like only the Windows runtime is affected.

Sample [pdf](https://github.com/Carael/MuPDFCore/blob/master/Demo/Jpeg2000_Sample.pdf) file.

**Comment by arklumpus** [comment]
Great, thank you!

I have just released version 1.2.7, which should fix the issue on Windows. It seems that it was working fine on macOS as well.

I'm closing this issue; feel free to reopen it if the problem persists even with 1.2.7. Thanks again for noticing the issue!

**Comment by Carael** [comment]
Thanks for a quick fix! I can confirm it works now on Windows.
